### IMPORT PACKAGE
install.packages("ggplot2")
install.packages("dplyr")
install.packages("ggthemes")
install.packages("extrafont")
library(ggplot2)
library(dplyr)
library(ggthemes)
library(extrafont)

font_import()
fonts()

### IMPORT DATA
setwd("~/Downloads")
netflix <- read.csv("Netflix Userbase.csv")
netflix
str(netflix)
head(netflix)

### DATA CLEANING
missing_values <- is.na(netflix)
sum(missing_values) #the dataset is complete without any missing values.

duplicates <- duplicated(netflix)
sum(duplicates) #there is no duplicated row in the dataset.

### DATA EXPLORATION
head(netflix)

netflix |>
  count(Subscription.Type)

# What is the distribution of users across different subscription types (Basic, Standard, Premium)?
users_subscription_type <- netflix |>
  count(Subscription.Type) |>
  arrange(desc(n))

ggplot(users_subscription_type, aes(Subscription.Type, n, fill = Subscription.Type)) +
  geom_col(width = 0.5) +
  geom_text(data = users_subscription_type, 
            aes(label = n), vjust = -0.5) +
  labs(title = "Distribution of users across different subscription types",
       subtitle = "What is the distribution of Netflix users across different subscription types?",
       x = "Subscription type", 
       y = "Number of users",
       fill = "Subscription type") +
  scale_fill_manual(values=c("#221F1F", "#DB0000", "#FF9900")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(size = 13), 
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10)),
        text = element_text(family = "Tahoma"))

# What is the overall revenue generated by each subscription type?
revenue_subscription_type <- netflix |>
  group_by(Subscription.Type) |>
  summarize(revenue_by_subscription_type = sum(Monthly.Revenue))

ggplot(revenue_subscription_type, aes(Subscription.Type, revenue_by_subscription_type, fill = Subscription.Type)) +
  geom_col(width = 0.7) +
  labs(title = "Overall revenue generated by each subscription type", 
       subtitle = "What is the overall revenue generated by each subscription type?",
       x = "Subscription type", 
       y = "Revenue",
       fill = "Subscription type") +
  scale_fill_manual(values = c("#221F1F", "#DB0000", "#FF9900")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(size = 13), 
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10)),
        text = element_text(family = "Tahoma"))


# How does the revenue differ across various countries?
revenue_by_countries <- netflix |>
  group_by(Country) |>
  summarize(revenue_by_countries = sum(Monthly.Revenue))

ggplot(revenue_by_countries, aes(Country, revenue_by_countries, fill = Country)) +
  geom_col(width = 0.6) +
  geom_text(data = subset(revenue_by_countries, Country %in% c("Spain", "United States", "Canada")),
            aes(label = revenue_by_countries), vjust = -0.5) +
  labs(title = "Netflix's revenue by country", 
       subtitle = "How does the revenue differ across various countries?",
       x = "Country", 
       y = "Revenue") +
  scale_fill_manual(values = c("#221F1F", "#DB0000", "#FF9900", "#B9E8E0", "#FFD699", "#FC4A47", "#FFAC1D", "#000000", "#FFCE22", "#3F3D56")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(size = 13), 
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10)),
        text = element_text(family = "Tahoma"))

user_by_country <- netflix |>
  group_by(Country) |>
  summarise(total_users_by_country = sum(User.ID))

ggplot(user_by_country, aes(Country, total_users_by_country, fill = Country)) +
  geom_col(width = 0.6) +
  labs(title = "Number of users by country", 
       subtitle = "How does the number of users differ across various countries?",
       x = "Country", 
       y = "Number of users") +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_manual(values = c("#221F1F", "#DB0000", "#FF9900", "#B9E8E0", "#FFD699", "#FC4A47", "#FFAC1D", "#000000", "#FFCE22", "#3F3D56")) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(size = 13), 
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10)),
        text = element_text(family = "Tahoma"))


# How does the overall revenue vary over time by each subscription type?
netflix$Join.Date <- as.Date(netflix$Join.Date, format = "%d-%m-%y")
netflix$Last.Payment.Date <- as.Date(netflix$Last.Payment.Date, format = "%d-%m-%y") #this is not really necessary

revenue_by_time_subscription <- netflix |>
  mutate(Join.Month = format(Join.Date, "%Y-%m")) |>
  group_by(Join.Month, Subscription.Type) |>
  summarise(Total_Revenue = sum(Monthly.Revenue))

ggplot(revenue_by_time_subscription, aes(x = Join.Month, y = Total_Revenue, color = Subscription.Type)) +
  geom_point() +
  labs(title = "Overall revenue trend over time by subscription type",
       x = "Time (Month-Year)",
       y = "Total Revenue",
       color = "Subscription Type") +
  scale_color_manual(values = c("#221F1F", "#DB0000", "#FF9900")) +
  theme_fivethirtyeight() +
  theme(axis.title.x = element_text(margin = margin(t = 10), size = 13), 
        text = element_text(family = "Tahoma"))

#there was a sudden rise in Netflix revenue between May and November 2022

# What is gender distribution of Netflix users?
gender_netflix_user <- netflix |>
  group_by(Gender) |>
  count()

ggplot(gender_netflix_user, aes(Gender, n, fill = Gender)) +
  geom_col(width = 0.6) +
  labs (title = "Gender distribution of Netflix users",
        subtitle = "What is gender distribution of Netflix users?",
        y = "Number of users") +
  scale_fill_manual(values = c("#221F1F", "#DB0000")) +
  theme_fivethirtyeight() +
  theme(axis.title.x = element_text(margin = margin(t = 10), size = 13), 
        axis.title.y = element_text(margin = margin(r = 10), size = 13),
        text = element_text(family = "Tahoma"))

# What is average age distribution of Netflix users?
age_breakpoints <- c(20, 30, 40, 52)
age_labels <- c("20-30", "31-40", "41-51")

netflix$Age.Group <- cut(netflix$Age, breaks = age_breakpoints, labels = age_labels, right = FALSE)

age_netflix_user <- netflix |>
  group_by(Age.Group) |>
  count() 

ggplot(age_netflix_user, aes(Age.Group, n, fill = Age.Group)) +
  geom_col(width = 0.8) +
  labs (title = "Age distribution of Netflix users",
        subtitle = "What is average age distribution of Netflix users?",
        x = "Age groups",
        y = "Number of users",
        fill = "Age groups") +
  scale_fill_manual(values = c("#221F1F", "#DB0000", "#FF9900")) +
  theme_fivethirtyeight() +
  theme(axis.title.x = element_text(margin = margin(t = 10), size = 13), 
        axis.title.y = element_text(margin = margin(r = 10), size = 13),
        text = element_text(family = "Tahoma"))

#Are there any differences in user behavior based on device type (e.g., Smart TV, Mobile, Desktop, Tablet)?
device_user_netflix <- netflix |>
  group_by(Device) |>
  count()

ggplot(device_user_netflix, aes(Device, n, fill = Device)) +
  geom_col(width = 0.8) +
  labs(title = "User behaviour based on device type",
       subtitle = "Are there any differences in user behavior based on device type?",
       y = "Number of users") +
  scale_fill_manual(values = c("#221F1F", "#DB0000", "#FF9900", "#FC4A47")) +
  theme_fivethirtyeight() +
  theme(axis.title.x = element_text(margin = margin(t = 10), size = 13), 
        axis.title.y = element_text(margin = margin(r = 10), size = 13),
        text = element_text(family = "Tahoma")) #all four devices are equally popular with netflix users

# Are there any differences in revenue generation between different age groups?
revenue_generation <- netflix |>
  group_by(Age.Group) |>
  summarize(revenue = sum(Monthly.Revenue))

ggplot(revenue_generation, aes(Age.Group, revenue, fill = Age.Group)) +
  geom_col(width = 0.6) +
  labs(title = "Netflix's revenue generation between different age groups",
       subtitle = "Are there any differences in revenue generation between different age groups?",
       x = "Age groups",
       y = "Revenue",
       fill = "Age groups") +
  scale_fill_manual(values = c("#221F1F", "#DB0000", "#FF9900")) +
  theme_fivethirtyeight() +
  theme(axis.title.x = element_text(margin = margin(t = 10), size = 13), 
        axis.title.y = element_text(margin = margin(r = 10), size = 13),
        text = element_text(family = "Tahoma"))

# Are there any patterns in the last payment date? How frequently do users make payments?
current_date <- Sys.Date()
netflix <- netflix %>%
  mutate(Days_Since_Last_Payment = as.numeric(current_date - Last.Payment.Date))

ggplot(netflix, aes(x = Days_Since_Last_Payment)) +
  geom_histogram(binwidth = 6, color = "black", fill = "white") +  
  labs(title = "Distribution of Days Since Last Payment",
       subtitle = "How frequently do users make payments?",
       x = "Days Since Last Payment",
       y = "Frequency") +
  theme_fivethirtyeight() +
  theme(axis.title.x = element_text(margin = margin(t = 10), size = 13), 
        axis.title.y = element_text(margin = margin(r = 10), size = 13),
        text = element_text(family = "Tahoma"))

summary_stats <- netflix %>%
  summarise(Mean_Days_Since_Last_Payment = mean(Days_Since_Last_Payment, na.rm = TRUE),
            Median_Days_Since_Last_Payment = median(Days_Since_Last_Payment, na.rm = TRUE),
            Min_Days_Since_Last_Payment = min(Days_Since_Last_Payment, na.rm = TRUE),
            Max_Days_Since_Last_Payment = max(Days_Since_Last_Payment, na.rm = TRUE))

summary_stats


